
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FOS.DataLayer
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_CompetitorActivities
{

    public int ID { get; set; }

    public Nullable<int> SOID { get; set; }

    public Nullable<System.DateTime> ActivityDate { get; set; }

    public Nullable<int> CompetitorID { get; set; }

    public Nullable<int> ActivityTypeID { get; set; }

    public string Remarks { get; set; }

    public string PicturePath { get; set; }

    public string VideoPath { get; set; }

    public string VoicePath { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public bool IsActive { get; set; }

    public Nullable<int> ZoneID { get; set; }

    public Nullable<int> CityID { get; set; }

    public bool IsDeleted { get; set; }

}

}
