
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FOS.DataLayer
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_SOProdKnowledgeCompFeed
{

    public int ID { get; set; }

    public Nullable<int> SOID { get; set; }

    public Nullable<int> HeadID { get; set; }

    public Nullable<decimal> ProductKnowledge { get; set; }

    public Nullable<decimal> CompFeed { get; set; }

    public Nullable<int> FinancialYearID { get; set; }

    public string Quarter { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

}

}
